# Generated by Django 4.1.3 on 2023-01-02 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=50, verbose_name='Наименование услуги')),
                ('price', models.IntegerField(verbose_name='Цена работ')),
            ],
        ),
        migrations.CreateModel(
            name='User_Client',
            fields=[
                ('name_client', models.CharField(help_text='Например: Иванов Пётр Сергеевич', max_length=50, primary_key=True, serialize=False, verbose_name='ФИО клиента')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('name_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.user_client', verbose_name='ФИО клиента')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Services.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(related_name='orders', to='Services.services'),
        ),
    ]
