# Generated by Django 4.1.3 on 2023-01-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(default='470801202323', max_length=50, verbose_name='Номер заказа'),
        ),
    ]
