# Generated by Django 4.1.3 on 2023-01-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
