# Generated by Django 4.1.3 on 2023-01-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, verbose_name='Наименование услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=20, verbose_name='Наименование работ')),
                ('price', models.IntegerField(null=True, verbose_name='Цена работ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='Services.service')),
            ],
        ),
    ]
