# Generated by Django 4.1.3 on 2023-01-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_service_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work',
            field=models.CharField(max_length=30, verbose_name='Наименование работ'),
        ),
    ]
