# Generated by Django 4.1.3 on 2023-01-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_order_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ConnectionOrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(default='280801202312', max_length=50, verbose_name='Номер заказа'),
        ),
    ]
