# Generated by Django 4.1.5 on 2023-01-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_rename_client_connectionorderitem_alter_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(default='222201202328', max_length=50, verbose_name='Номер заказа'),
        ),
    ]
