# Generated by Django 4.1.3 on 2023-01-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_work_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='Services.service', verbose_name='Наименование услуги'),
        ),
    ]
