# Generated by Django 4.1.3 on 2023-01-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_order_totalorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalorder',
            name='quantity',
        ),
    ]
