# Generated by Django 4.1.3 on 2023-01-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_remove_totalorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalorder',
            name='name_client',
        ),
        migrations.RemoveField(
            model_name='totalorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='totalorder',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='name_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Services.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Services.totalorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='work',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec', to='Services.totalorder', verbose_name='Заказ'),
        ),
    ]
