# Generated by Django 4.1.3 on 2023-01-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_alter_work_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.work'),
        ),
    ]
