# Generated by Django 4.1.3 on 2023-01-03 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_remove_work_order_order_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalorder',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.client'),
        ),
    ]
