# Generated by Django 4.1.3 on 2023-01-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0011_totalorder_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name_client',
        ),
    ]
