# Generated by Django 4.1.3 on 2023-01-03 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_remove_order_name_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Services.client'),
        ),
    ]
