# Generated by Django 4.1.3 on 2023-01-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0014_remove_order_name_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalorder',
            name='client',
        ),
    ]
