# Generated by Django 4.1.3 on 2023-01-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0015_remove_totalorder_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='name_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Services.client'),
        ),
        migrations.DeleteModel(
            name='TotalOrder',
        ),
    ]
