# Generated by Django 4.1.3 on 2023-01-03 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0016_remove_order_order_order_name_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.client')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Services.totalorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='work',
            name='ordering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec', to='Services.totalorder'),
        ),
    ]
