# Generated by Django 4.1.3 on 2023-01-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0017_totalorder_order_order_work_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.RemoveField(
            model_name='work',
            name='ordering',
        ),
        migrations.DeleteModel(
            name='TotalOrder',
        ),
    ]
