# Generated by Django 4.1.3 on 2023-01-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0018_remove_order_order_remove_work_ordering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='work_order',
        ),
        migrations.AddField(
            model_name='order',
            name='work_order',
            field=models.ManyToManyField(null=True, to='Services.work'),
        ),
    ]
