# Generated by Django 4.1.3 on 2023-01-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0019_remove_order_work_order_order_work_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForInlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_order',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='Services.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Services.work'),
        ),
        migrations.AddField(
            model_name='order',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.forinlineorder'),
        ),
    ]
