# Generated by Django 4.1.3 on 2023-01-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0021_remove_order_client_forinlineorder_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена работ'),
        ),
    ]
