# Generated by Django 4.1.3 on 2023-01-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0022_alter_work_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена работ'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='Services.service', verbose_name='Наименование услуги'),
        ),
        migrations.AddField(
            model_name='order',
            name='work',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование работ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=20, null=True, verbose_name='Наименование услуги'),
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
