# Generated by Django 4.1.3 on 2023-01-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0023_remove_order_order_order_price_order_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work',
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=50, verbose_name='Наименование работ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена работ')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='Services.service', verbose_name='Наименование услуги')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Services.work'),
        ),
    ]
