# Generated by Django 4.1.3 on 2023-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0024_remove_order_price_remove_order_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена работ'),
        ),
    ]
