# Generated by Django 4.1.3 on 2023-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0027_alter_work_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(null=True, related_name='order', to='Services.work'),
        ),
    ]
