# Generated by Django 4.1.3 on 2023-01-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0028_remove_order_order_order_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.RemoveField(
            model_name='work',
            name='price',
        ),
        migrations.RemoveField(
            model_name='work',
            name='service',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена работ'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='Services.service', verbose_name='Наименование услуги'),
        ),
        migrations.AddField(
            model_name='order',
            name='work',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование работ'),
        ),
    ]
